### ISSUE TITLE
Is it safe to flash esp8266/Arduino?

### ISSUE THREAD

**Issue by lucabelluccini** [pimoroni/espiot-phat#9]
Hello,
Is it safe to flash the esp8266/Arduino firmware from https://github.com/esp8266/Arduino?

Thank you in advance

**Comment by Gadgetoid** [comment]
Sorry for the delayed response- I've not played with the esp8266 much at all, so I honestly don't know for sure, but I would expect it's safe to flash anything as long as it doesn't modify or overwrite the bootloader (if that's even possible).
